---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.10.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 5m
  releaseName: ingress-nginx
  values:
    controller:
      enabled: true
      service:
        loadBalancerIP: "${NGINX_IP}"
      admissionWebhooks:
        enabled: false
