---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-tailscale
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
spec:
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  type: LoadBalancer
  loadBalancerClass: tailscale
