apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - volumes.yaml

configMapGenerator:
  - name: home-assistant-config
    namespace: home-assistant
    literals:
      - TZ="Europe/London"
