---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: home-assistant
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: home-assistant
  chart:
    repository: https://k8s-at-home.com/charts/
    name: home-assistant
    version: 6.0.1
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: home-assistant
spec:
  rules:
    - host: home-assistant.home.eadie.net
      http:
        paths:
          - backend:
              serviceName: home-assistant
              servicePort: 8123
            path: /