apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: grafana.pi.lan
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: 80
            path: /