apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  releaseName: prometheus
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus
    version: 11.7.0
  values:
    server:
      strategy:
        type: Recreate
      persistentVolume:
        enabled: true
        accessModes:
          - ReadWriteMany
        size: 8Gi
    kubeStateMetrics:
      enabled: true
    kube-state-metrics:
      image:
        repository: carlosedp/kube-state-metrics
        tag: v1.9.6
    alertmanager:
      enabled: false
    pushgateway:
      enabled: false
