apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  releaseName: prometheus
  chart:
    repository: https://prometheus-community.github.io/helm-charts/
    name: prometheus
    version: 13.3.2
  values:
    server:
      strategy:
        type: Recreate
      persistentVolume:
        enabled: true
        accessModes:
          - ReadWriteMany
        size: 8Gi
    kubeStateMetrics:
      enabled: true
    kube-state-metrics:
      image:
        repository: carlosedp/kube-state-metrics
        tag: v1.9.6
    alertmanager:
      enabled: false
    pushgateway:
      enabled: false
    nodeExporter:
      enabled: true
      extraArgs:
        collector.mountstats: ""