---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt-data
spec:
  storageClassName: ""
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NFS_SERVER_IP}
    path: "${NFS_BASE_PATH}/Kubernetes/Kubernetes/config/zigbee2mqtt"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data
  namespace: zigbee2mqtt
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: zigbee2mqtt-data
