apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth
    namespace: monitoring
type: Opaque
data:
    client_id: ENC[AES256_GCM,data:FOiPSYBgtlKx28LWSK5reMxB359biq3e,iv:1wkoJaGZLEy5TU/l0jFIy6Mb6bpyQkAVBEICFiwi/pQ=,tag:uzN1UmkWlGsPsBQRsha3Vg==,type:str]
    client_secret: ENC[AES256_GCM,data:/UfIsmNAzZ3sCErvT9clzpgj0dYeZH+EsG9VF+6ObopJXtHMK19kYcpm0THmne9VXrc/z7VGb/Q/5Skqz7liFEjnx6gKx2/KZ1/5/2StneI52qeCtD50Xw==,iv:iJHuSEbFKD1mLQI7ByIK/7hcHULHVlqoDCj8nKkQWAo=,tag:FpDZxLlCIR6WRbmicSf+TA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T13:38:34Z"
    mac: ENC[AES256_GCM,data:m6qM2xCjzMfzEIZLYazSowunVHWofXPsdc1bhkScqsaihn/r8P6F0M15xIz7gUdaUJI1iqspdZy2TPsTJgD3QkLawXFBrI61gCZ0w4KI7G5J6n3qGMjEVJRpIiR8gfTolEyqrWVeclzHpWIuognyE0ebBp88GagTu9+sQcLpNvk=,iv:fLzZ3UlPi4UNPLjx+QSDYGZe6tl0kyzGxW/rnCbxjgk=,tag:8ApoLCXbxA0q+k74CNvmRQ==,type:str]
    pgp:
        - created_at: "2026-06-14T13:38:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAx7w+dz/TE0ZARAAr66zYI4RFfnIj9YCc4vpHNN9c/CJKhixasuMO09ozS1a
            0AqxTUuD7hytPY+DAcjzKr2MqT1VfwC0lhv5AQKfOCcJvIFpO4lapzgpiEkS+Y4x
            1anNG6MLFvUx2d0MHuDZFkYkuNSS01WA3toIdf4iGsBQcPCCtZxIQurtcbkSMK3n
            z+XeC18o/rw/HNhaqUwNZDc84OxFnlQtVTxCi1UaZvJShJOFiLGg1HEY+D6yfPLK
            JN4Se1ijuLfGXCOgnMIFvytK+TP1uDU8C1XZ+3NzlM8HHbfr/Twe8PxHQBhtrV6l
            AaCu1PNj3Ft/pdUzjzc1YG/OXu1hYHJA73JgANnm1Qo1WGRjApxe/6GgBbVTznku
            sMmAPrH164U4gj5Ua/J+isGky4JEYXQc6nVAAL+fjS70SCGyrYntJjuns2anarVI
            SFcqEnVrNljPJS5jTq5bgOf0JknmOSMOzZYGkCN2mkWi2Jk4wdOmvWh6kav6XIgH
            dRxTT5ZQetUqccgJeh87MUKMNhLGLvqLh3XfZ2+wPmTass0lFj/2R/Rf+vdXTKgy
            CAXSNXA72fGDNxNARNlAJNFKi71z1tRyMb0V0o8ygh7mRkWXsCgKfSYEmMlwC/+j
            uYQrX6BRsLezdHOY2VvTMzLT4Aqmw9jeI2iJ805drHc+35JhQF5iBOyHmEwI4bfS
            XgExayLo1ELVkFzaroIXKBUNhXnTLBaALLUVfy0oAv3j3GPUXnJbrn95rfl6DFsU
            BTWIvaxWPC+P0C1VaJRtfgE6JiQorIsOqBmqfnauM1BGxUNMSuMfVkV52CK/Xio=
            =8tEV
            -----END PGP MESSAGE-----
          fp: D3D53D22793960761CDE144C0EF386217DAD811D
    version: 3.13.1
