---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: metallb
  chart:
    repository: https://charts.bitnami.com/bitnami/
    name: metallb
    version: 0.1.23
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.1.200-192.168.1.249