---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx/
    name: ingress-nginx
    version: 3.31.0
  values:
    rbac:
      create: true
