apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-exporter
  labels:
    app: nest-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-exporter
  template:
    metadata:
      labels:
        app: nest-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
    spec:
      containers:
      - name: nest-exporter
        image: theeadie/nest-exporter:latest@sha256:a9215a1d14cb4523d1a755c5f824dc4016f59b876f605da6a3773ec9e1c237f3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: NestExporter_NestApi__ClientId
          valueFrom:
            secretKeyRef:
              name: nest-exporter
              key: NestApi__ClientId
        - name: NestExporter_NestApi__ClientSecret
          valueFrom:
            secretKeyRef:
              name: nest-exporter
              key: NestApi__ClientSecret
        - name: NestExporter_NestApi__ProjectId
          valueFrom:
            secretKeyRef:
              name: nest-exporter
              key: NestApi__ProjectId
        - name: NestExporter_NestApi__RefreshToken
          valueFrom:
            secretKeyRef:
              name: nest-exporter
              key: NestApi__RefreshToken
---
apiVersion: v1
kind: Service
metadata:
  name: nest-exporter
spec:
  selector:
    app: nest-exporter
  ports:
    - protocol: TCP
      port: 80
