apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - test-site.yaml
  - pihole.yaml
  - jellyfin.yaml
  - monitoring.yaml
  - hue-exporter.yaml
  - truenas.yaml
  - homer.yaml
  - home-assistant.yaml
  - adguard.yaml
  - mosquitto.yaml
