---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-config
  namespace: home-assistant
spec:
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
