apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - volumes.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: zigbee2mqtt-config
    namespace: home-assistant
    files:
      - configuration.yaml
