{
 "title": "Home",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Actual Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nest_thermostat_actual_temperature",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Target Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nest_thermostat_target_temperature",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nest_thermostat_humidity", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Heating",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nest_thermostat_status", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Living Room - Heating",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "nest_thermostat_actual_temperature",
     "legendFormat": "Actual"
    },
    {
     "expr": "nest_thermostat_target_temperature",
     "legendFormat": "Target "
    },
    { "expr": "nest_thermostat_status", "legendFormat": "Heating On" }
   ]
  },
  {
   "title": "Living Room - Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "nest_thermostat_humidity", "legendFormat": "Humidity" }
   ]
  }
 ]
}