apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  releaseName: grafana
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: grafana
    version: 5.3.0
  values:
    persistence:
      enabled: true
      size: 10Gi
    sidecar:
      image: 
        repository: ramsrib/k8s-sidecar
        tag: latest
      datasources:
        enabled: true
        label: grafana_datasource
      dashboards:
        enabled: true
        label: grafana_dashboard
