apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: monitoring
  namespace: monitoring
spec:
  rules:
  - host: node1.local
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 80
