apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  releaseName: prometheus
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus
    version: 11.3.1
  values:
    alertmanager:
      enabled: false
    kubeStateMetrics:
      enabled: false
    pushgateway:
      enabled: false