helmOperator:
  create: false
git:
  url: "git@github.com:TheEadie/k8s-cluster.git"
  branch: master
  path: azure
  label: flux-sync-azure
registry:
  rps: 1
  burst: 1
memcached:
  enabled: true
syncGarbageCollection:
  enabled: true
  dry: false
prometheus:
  enabled: true
  serviceMonitor:
    create: false
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux