---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open-media-vault
  namespace: open-media-vault
  labels:
    app: open-media-vault
spec:
  namespaceSelector:
    matchNames:
      - open-media-vault
  selector:
    matchLabels:
      app: open-media-vault
  endpoints:
    - port: node-exporter
      path: /metrics
      relabelings:
        - targetLabel: kubernetes_node
          replacement: pi1
