---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: "3.29.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 1h
  releaseName: ingress-nginx
  values:
    controller:
      enabled: true
    defaultBackend:
      enabled: false
    admissionWebhooks:
      enabled: false