apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: cluster-secrets
stringData:
    #ENC[AES256_GCM,data:DN8fQNnaZiE=,iv:R1Ou6NJmtrgacCcufEhVk282gQfP9V7ze+AMhlmQBDs=,tag:tbOaEG+ahipKJnlFJBPmng==,type:comment]
    SECRET_DOMAIN: ENC[AES256_GCM,data:WWUK4950VwdL1xslyWuA2+x5zA==,iv:5F47CSqeQL8pNY3hkZ4stnlqBz2DsjU/zaYmq4YUhww=,tag:HovB7E8+nS7ZwDYu1P+Pvw==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:TkIKiDi6A6/qvMjkAAT2,iv:FAc88y3vKsPzuhQcZZPlLSO4FfJtoa/7CcsngmDGoOk=,tag:DYhfYlxf83KuhWgdT00rAw==,type:str]
    #ENC[AES256_GCM,data:B+t45HM5zOrOiyI=,iv:jAMiKJ5aNk+OkQ1hfOQ2QIGk2iK6JiX+ROFXOE3+6Zg=,tag:7plrX5K2QWb/CeKIvEexIg==,type:comment]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:dq9x2jTwWQLJFvMFVd1Ud7rItq66CqISSA1ynMV3rLLR9oIp5vxdtw==,iv:4/N+uxqT8dMOx3wrn9BSg/+6x0q1PP5kfdf8m9xSK/Y=,tag:YmIf5CDABA9cgl/1fwgY7A==,type:str]
    #ENC[AES256_GCM,data:DCLI6keSaNM=,iv:Z6vNGn684AV7TqlNzHU4lKliB3/uxMv/jt/ALp/Apd0=,tag:v0Q5fe9T7WeIHP9W1bGdEg==,type:comment]
    ZITADEL_ADMIN_PASSWORD: ENC[AES256_GCM,data:i/eorREOywu0FZhZGj/3/cISvron,iv:+Y2O23pPbvRKQr+/HYAU2rLveJNC+FJ+cuW7CML4Q6U=,tag:nV3L7cg2MNn1xCJA8A2J6w==,type:str]
    #ENC[AES256_GCM,data:+CEOg4E=,iv:vJ4LXV8ZwCElOs32cHEaOWDDhy1dqUm5CfxZRKvN6/E=,tag:+Gw0b/D9vmw/sCoxf9wRVQ==,type:comment]
    FLUX_SLACK_URL: ENC[AES256_GCM,data:8HG7GKxvvNY5WcPg742EUk5w3QsdpZUWORLrURRzXl/zh/UORQRXIT6mEVtNe1KFZ3/k4U9j+NNocX4e441i7pR/FLMONM0xkYkzsyEyuw==,iv:4b3QANlkHAuMfeBco+xbwO1aAkmWHu/rDaDyl4I3XfU=,tag:BlwXbBFwlwWX+Y0uJ5wMTQ==,type:str]
    ALERTMANAGER_SLACK_URL: ENC[AES256_GCM,data:uisvB3sMKx9nvdmURhueUk7SSUurGdwoLGPmFj3WleZ+5bjYUmKAEwX1FC4hW8hjUu0/Ti2l2Jvpl047twRegfI1642aJrv8G9CE8++EWQ==,iv:4F6o7foOEMt/kE0C5B6FSOe+RC+eZd1ebDlKXQjtOn4=,tag:Cz4TPn6tOEfMNWtKjmEtmg==,type:str]
    #ENC[AES256_GCM,data:f+3MqS5JfrBmzA==,iv:ylEwWEui31JzhXHWe+iFClrDci7SxyuZJnMMvGeyFyY=,tag:Q3GRU4zPFOdYt2zmTR5P2g==,type:comment]
    TAILSCALE_CLIENT_ID: ENC[AES256_GCM,data:5Vwg60TCyE72CU55gUvGd1o=,iv:461vXbBElOgbkDXtpIdQNKODUaeYBkUTm8jdj3xX+po=,tag:PAYo8XXlZkuXDNRYffNXnA==,type:str]
    TAILSCALE_CLIENT_SECRET: ENC[AES256_GCM,data:2u+04prCKEyVFbkEL1KDtm6AkpifY3oGzByD+jdUBN1fHR5YeNE5FMcQws+lnlme4jbop2ZKOF7KJLQbFmTY,iv:VwOB5TPTbIh/G1Gjv5AHH6OoJUuQPR/1XBstzMNMy7s=,tag:wptjtnko2zuADzdWxAMh2A==,type:str]
    ZITADEL_MASTERKEY: ENC[AES256_GCM,data:nn9d5Rt2AwiRumuKtHAOmhmNO/4KmEmI3vub8y3YavU=,iv:EwN1yKwy3A4Jy/AhULrvmctaZztw9LLYkQEzG5q07GM=,tag:hZ4IM1IVymjcF8x9Uwes/w==,type:str]
    ZITADEL_DB_PASSWORD: ENC[AES256_GCM,data:+16Fc7Xj61nOhm+L3BwIR+A+dBr568UJixMTPqZrzwo=,iv:a2Y0kmMg9SVoRFJ2HilrvhTgkTUk10vgowSp8hqmdHE=,tag:EJT3I5HTieQRbQbcvF22EQ==,type:str]
    ZITADEL_DB_ADMIN_PASSWORD: ENC[AES256_GCM,data:DlNWhxONF8+ParcqxImUnZAr6cHKKKk/mURaC+wNc4Y=,iv:Y84Nuc7IX4eFpYbzMlybQQuE3XeTqGBo351F/jm7UUo=,tag:yg5kakBHLDYbPE9Dw7T7Dg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T13:40:54Z"
    mac: ENC[AES256_GCM,data:Ba3knRJmlRwKxPjunNjyV+yKmF824H1ewF928zMWJAc1DJFOCOKi1AvfvatX1qOW63k/yOaYexiOep6ZGzUEheFJyaD1knQ9Y0dHVFTgAnPCrq9NGQyxETdKk9mAi2EdHVirM4Q20y0cgOL4pyhv6PcXPL1bt1BsueTZbAW0zf4=,iv:rwE8tNtECCvU//lv38j2TqIZ6zqY8H+w5lzi/rUwq3A=,tag:n9my7Jj+eHUhW0kvqiGupQ==,type:str]
    pgp:
        - created_at: "2026-06-14T13:40:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAx7w+dz/TE0ZARAAhu3alrrTP6AwGDOvL0tWB63pKUbJqGyuLsnMGoEuHGdM
            J6uVqBZA92qBHLJr+9qpodE3Ddf/FBVaPKw+YIdsR8WwEjL0eOZVnvAVzXPy1Dt6
            mnXD2Wwb77p4HsXBY8L/SMm19rls0xmxnK2PZLG8umooXU2zyZqknmqWfxFwdmJk
            I9SfAOW7aJ4FyaBuUMpkos1Lhq9z4S5VI5bwsdTo7rQfuesEi1gHIUEy81S/Kcb1
            bgDIwlochV/3zyQQ6REGPydmBPX0IbNGGPbqGDBFRzfk/tPD+/nrrL7sBDxSJxN+
            2Duumiwk2k3vYa7g3yn4ZfXh1Ma69gp20WgUiuViWIuVuWngnKO/yywyxg8256ma
            itgAU5Y2rOuuo1qmyQNPGduUysSOItO6m0HqIXoQMOBwF9iMssEryVyzTerUuuRW
            bgmslWBEZoZ1NInqB3lFN4/gcc30rFgFF/BMjDi8RTwGTR+dXNif2O11u9iBVQy0
            HMTgUFVFraYe6kasbwKXzz5W4yoBSZUOfGkByPNd1yjLeXYc6L1UchvQwxx/K2Tw
            ag2joxDrQEL0agUdere/en4/wqqFcnwxhuPOttwhISVB81nVYTgAQ00zxhLxrR2q
            VoN87LaLgtgrvpREHJTiAqJ5RIc/Gefk7BE55NSMEoLQP8F2tqAQ6DTee2ko8K/S
            XgEgs5Yr67a4gzDSNmJd+XwsdbeI9Wb4v4Ni7t/iCVsUIKkicIutiUrEhCLW6si1
            ZxRA24FknV+mqyRe5rHyF1RptCm40N9yyIaiq+UeoRq9vZsIUN+oxt3PyR9b7wk=
            =zpXA
            -----END PGP MESSAGE-----
          fp: D3D53D22793960761CDE144C0EF386217DAD811D
    version: 3.13.1
