apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server
          ports:
            - containerPort: 25565
              name: http
              protocol: TCP
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
          env:
            - name: EULA
              value: "TRUE"
          stdin: true
          tty: true
          livenessProbe:
            exec:
              command: ["mc-health"]
            initialDelaySeconds: 120
            periodSeconds: 60
          readinessProbe:
            exec:
              command: ["mc-health"]
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 12
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data
