---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-data
spec:
  storageClassName: ""
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${PI_NFS_SERVER_IP}
    path: "/export/Kubernetes/config/minecraft"
  mountOptions:
    - nfsvers=3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: minecraft
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: minecraft-data
