---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: plex
  chart:
    repository: https://k8s-at-home.com/charts/
    name: plex
    version: 2.0.4
  values:
    claimToken: "claim-EHj_ou-SGGpY4ikivECq"
    persistence:
      config:
        claimName: "plex-config-claim"
      data:
        claimName: "plex-data-claim"
    serviceTCP:
      type: LoadBalancer
      port: 32400
      annotations:
        metallb.universe.tf/address-pool: default
        metallb.universe.tf/allow-shared-ip: plex-svc
      loadBalancerIP: 192.168.50.203
    serviceUDP:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: default
        metallb.universe.tf/allow-shared-ip: plex-svc
      loadBalancerIP: 192.168.50.203
