---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-exporter
  namespace: nest-exporter
  labels:
    app: nest-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-exporter
  template:
    metadata:
      labels:
        app: nest-exporter
    spec:
      containers:
      - name: nest-exporter
        image: theeadie/nest-exporter:2.0.6@sha256:cbfd7a69920dea04e04c694cbbd32d15bfbabd7e27927e3c9cdfcb621075f536
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        env:
        - name: NestExporter_NestApi__ClientId
          valueFrom:
            secretKeyRef:
              name: nest-exporter
              key: NestApi__ClientId
        - name: NestExporter_NestApi__ClientSecret
          valueFrom:
            secretKeyRef:
              name: nest-exporter
              key: NestApi__ClientSecret
        - name: NestExporter_NestApi__ProjectId
          valueFrom:
            secretKeyRef:
              name: nest-exporter
              key: NestApi__ProjectId
        - name: NestExporter_NestApi__RefreshToken
          valueFrom:
            secretKeyRef:
              name: nest-exporter
              key: NestApi__RefreshToken
