---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-exporter
  namespace: nest-exporter
  labels:
    app: nest-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-exporter
  template:
    metadata:
      labels:
        app: nest-exporter
    spec:
      containers:
        - name: nest-exporter
          image: theeadie/nest-exporter:2.0.56@sha256:79ed7c18ebf671f4c568cbad22e92191142fc11543cdc8fa1535dbbf83b4a4c8
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          env:
            - name: NestExporter_NestApi__ClientId
              valueFrom:
                secretKeyRef:
                  name: nest-exporter
                  key: NestApi__ClientId
            - name: NestExporter_NestApi__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: nest-exporter
                  key: NestApi__ClientSecret
            - name: NestExporter_NestApi__ProjectId
              valueFrom:
                secretKeyRef:
                  name: nest-exporter
                  key: NestApi__ProjectId
            - name: NestExporter_NestApi__RefreshToken
              valueFrom:
                secretKeyRef:
                  name: nest-exporter
                  key: NestApi__RefreshToken
            - name: NestExporter_OpenWeatherApi__ApiKey
              valueFrom:
                secretKeyRef:
                  name: nest-exporter
                  key: OpenWeatherApi__ApiKey
            - name: NestExporter_OpenWeatherApi__Longitude
              valueFrom:
                secretKeyRef:
                  name: nest-exporter
                  key: OpenWeatherApi__Longitude
            - name: NestExporter_OpenWeatherApi__Latitude
              valueFrom:
                secretKeyRef:
                  name: nest-exporter
                  key: OpenWeatherApi__Latitude
