apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy
    namespace: adguard
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:9gIhJKiyFsElTuGZb8L3fAdx,iv:khYhZgc5ZiJMvvJO91je5345Nrhtju8sBDTEVJeuGuY=,tag:ODAw86DngroAsHh7TFDQZA==,type:str]
    client-secret: ENC[AES256_GCM,data:y7ELDAAzSeOKHfgxpGBSanQGioFDaqxMjGGUrUBUulVKONVNkKdiJnsBMQvzjMwhU1B+bt5JM4YtKWXIrWDYYA==,iv:dAPP23pwjMdWjbt1Vn3qaLFERmOOznOpaDk47Vah07I=,tag:KkXqFD23C3E2z+S6uQnxSQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:aSq2UYYq9hEsWx3807NLqPzKHgy6HZIjN9r+0z4071fFGYn0PNOguTPjBkc=,iv:2zudLDGqIIVU+TVgF+PreV60yjukFD7qGudBCXWTSdg=,tag:5czxabqFRKc9ROav/gEL+Q==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T14:45:44Z"
    mac: ENC[AES256_GCM,data:j/VLS5fskrKDx7z+iZZ/OfwOc1uX4n5bBxBiTk8CNE+Srpctef4KM2yhvSYiKeUE4FF7U3l/NrkWfHjJ67l8KMMR8as9xv0uCWvuECLdNcbKwDC4SM9oShCb6bMDdNNwM04JEY29CJKnS5OYejCRX4L2p21XuWTI+OrpKNguCdg=,iv:+af40xvrEf0FT7q8QTKxTfIGoxnzITIByGRUEDf64bY=,tag:5m4sHxe0ALK73RBPe/f8+A==,type:str]
    pgp:
        - created_at: "2026-06-14T14:27:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAx7w+dz/TE0ZARAAi5cG8ibi/j8a+eQQ+uphI/mvkRsP6dir2dhF82umcxMP
            pHi0KYanpZofNOcUEGesfxodGQalXjD+k71bnNOV8cmzfap019kCrQ3b+KUIqQg7
            IL+N0HPQRjwPEMZX7Fnux4+Owmd9a/kcyMM/nHqV9uBHBjJ6xzKUP0fxjQV7ANKw
            +OETid7Vtu8Av7/7mVY8p86ZMyLzB7rofFKrWN8HuupywL4yPlHaPVv0Vx1x5NyT
            HqZ6CPm5b4KVg4gWsT/lSc0eZd8Z7fvL3ht5Hyy3UnH8u+A9xZSeXo9eeX83e6WS
            9rg8DizFuN7HKl13WYV+APcdDgp5GgmcRbYlxLcjkbKjo6mHLs0Tyswh6GNels2N
            1Qw3C2X9JLqIfMCkdMF97tajdM6dELf2bEG73/NZlNznFph4tCe/zP+til16frhQ
            4mCiC4BuXFVuFe5nOcUco678J80bYArTcRvwfAUWXNhj7c9NpsJxfbwvvLq92kir
            frVcaquaC5GcyiUx/LndbSV6k6y/HOd072BiYTrOfIxdEK5l0cmBedz2FAWzFbUy
            wuTm009bROdmS/LQpoE8TpsSDcWP2cDnZhCQ6C+2dkpNlTIMjjzaKniy1kFdYrye
            AXj69Y6L9kn65d2inJnkQVR9SomdcCxcxcr99zcrBPgyq7DFT6CkWuLpC3uCU3zS
            XgHoGSRWCzhXH/Rze9nlzOWZseDIFrCqQDp3JqHFbhB9AkoQlwmsgdOnSxlZGixZ
            9fbvp46VhWVGxnEIjf6cONU5yInaEYL7MZCAYMRcozwq9K9QcrRcQdhngDFUtt0=
            =+KDF
            -----END PGP MESSAGE-----
          fp: D3D53D22793960761CDE144C0EF386217DAD811D
    version: 3.13.1
