---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data
  namespace: adguard
spec:
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
