---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-config
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NFS_SERVER_IP}
    path: "/mnt/Kubernetes/Kubernetes/config/prometheus"
  mountOptions:
    - nfsvers=4.2
