---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: metallb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metallb
    version: 0.12.0
  values:
    controller:
      image:
        tag: v0.9.3
    speaker:
      image:
        tag: v0.9.3
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.1.240-192.168.1.255