---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx/
    name: ingress-nginx
    version: 3.1.0
  values:
    rbac:
      create: true
    controller:
      image:
        repository: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller"
        tag: "0.33.0"
        digest: sha256:0e57d295e67d431cecfb2d926bd71921ac8bf2ed585b37830fdfbefc5a3257a3
