---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  chart:
    spec:
      chart: metallb
      version: "2.3.6"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  releaseName: metallb
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.9.6
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.9.6
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.50.230-192.168.50.254