apiVersion: v1
kind: Namespace
metadata:
  name: metallb
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  chart:
    spec:
      chart: metallb
      version: "2.3.6"
      sourceRef:
        kind: HelmRepository
        name: metallb
  interval: 1h
  releaseName: metallb
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.9.4
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.9.4
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.50.230-192.168.50.254