# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

# Optional: Use external configuration file.
# Using this will ignore remaining config in this file
# externalConfig: https://example.com/server-luci/config.yaml

title: "Home"
subtitle: "Dashboard"
# documentTitle: "Welcome" # Customize the browser tab text
# logo: "assets/logo.png"
icon: "fas fa-home"

header: false
footer: false # set false if you want to hide it.

columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck:
  true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
  # You should set it to true when using an authentication proxy, it also reloads the page when a redirection is detected when checking connectivity.

defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'

theme: deafult

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links: []

services:
  - name: "Apps"
    icon: "fas fa-th"
    items:
      - name: "Jellyfin"
        icon: "fas fa-video"
        url: "http://jellyfin.${SECRET_DOMAIN}"
      - name: "TrueNAS"
        icon: "fas fa-hdd"
        url: "http://truenas.${SECRET_DOMAIN}"

  - name: "Internet"
    icon: "fas fa-wifi"
    items:
      - name: "Router"
        icon: "fas fa-network-wired"
        url: "http://${ROUTER_IP}"
      - name: "Pi-hole"
        icon: "fas fa-shield-alt"
        url: "https://pihole.${SECRET_DOMAIN}/admin"
        apikey: "${PIHOLE_API_TOKEN}"
        type: "PiHole"
      - name: "Speedtest"
        icon: "fas fa-tachometer-alt"
        url: "https://www.speedtest.net/"

  - name: "Monitoring"
    icon: "fas fa-eye"
    items:
      - name: "Grafana"
        icon: "fas fa-chart-pie"
        url: "https://grafana.${SECRET_DOMAIN}"
      - name: "Prometheus"
        icon: "fas fa-chart-line"
        url: "https://prometheus.${SECRET_DOMAIN}"
        type: Prometheus
