{
 "title": "Home",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Heating",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nest_thermostat_status", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Living room",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nest_thermostat_actual_temperature",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "(avg by (name) (nest_thermostat_actual_temperature))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "(avg by (name) (nest_thermostat_target_temperature))",
     "legendFormat": "Thermostat "
    },
    {
     "expr": "(avg by (name) (nest_thermostat_status))",
     "legendFormat": "Heating On"
    },
    {
     "expr": "(avg by (location) (openweather_temperature)) > 0",
     "legendFormat": "Outside"
    }
   ]
  },
  {
   "title": "Outside",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "openweather_temperature", "legendFormat": "Outside" }
   ]
  },
  {
   "title": "Thermostat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nest_thermostat_target_temperature",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Feels like",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "openweather_feelslike", "legendFormat": "Outside" }
   ]
  },
  {
   "title": "Living room",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nest_thermostat_humidity", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg by (name) (nest_thermostat_humidity))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "(avg by (location) (openweather_humidity)) > 0",
     "legendFormat": "Outside"
    }
   ]
  },
  {
   "title": "Outside",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "openweather_humidity", "legendFormat": "Outside" }
   ]
  }
 ]
}