---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-data
spec:
  storageClassName: ""
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NFS_SERVER_IP}
    path: "/mnt/Kubernetes/Kubernetes/config/adguard"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data
  namespace: adguard
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: adguard-data
