---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jellyfin
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: jellyfin
  chart:
    repository: https://k8s-at-home.com/charts/
    name: jellyfin
    version: 9.3.0
  values:
    persistence:
      config:
        enabled: true
        existingClaim: "jellyfin-config-claim"
      media:
        enabled: true
        existingClaim: "jellyfin-media-claim"
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: jellyfin
spec:
  rules:
    - host: jellyfin.home.eadie.net
      http:
        paths:
          - backend:
              serviceName: jellyfin
              servicePort: 8096
            path: /
