---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/config/jellyfin"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/share/Videos"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi