---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 5m
  chart:
    spec:
      chart: jellyfin
      version: 9.5.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    persistence:
      config:
        enabled: true
        existingClaim: "jellyfin-config"
      media:
        enabled: true
        existingClaim: "jellyfin-media"
    resources:
      requests:
        cpu: 200m
        memory: 1028Mi
      limits:
        memory: 4096Mi