---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: samba
  name: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: samba
    spec:
      containers:
      - image: dperson/samba
        name: samba-server
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
        args:
          # disable recycle bin
          - -r
          - -s
          - "share;/share;yes;no;;;;;"
        ports:
          - name: one
            containerPort: 139
          - name: two
            containerPort: 445
        volumeMounts:
          - name: share
            mountPath: /share
      volumes:
        - name: share
          hostPath:
            path: /mnt/data/share/
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: samba
  name: samba
  annotations:
    metallb.universe.tf/allow-shared-ip: "default"
spec:
  ports:
  - name: one
    port: 139
    protocol: TCP
    targetPort: 139
  - name: two
    port: 445
    protocol: TCP
    targetPort: 445
  selector:
    app: samba
  type: LoadBalancer
  loadBalancerIP: 192.168.50.202
status:
  loadBalancer: {}
