apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: cluster-secrets
stringData:
    #ENC[AES256_GCM,data:c8JUgS/B8rM=,iv:pgGVjT5EwoZWwh9aClwBcqa4OT7ZtT3mRDdm4LPumOc=,tag:gtQxD97f7sYTePi+eHyVfw==,type:comment]
    SECRET_DOMAIN: ENC[AES256_GCM,data:CQ+eccFjENnJh9BL,iv:q0U1PyPXoMxU/DbTGwqiD5slvXfQ6T1U3NTda8mAwfU=,tag:QScIcijhohAYvAgYc7jAVA==,type:str]
    #ENC[AES256_GCM,data:UKtVt4WFr4hj39cuyP8=,iv:TCNmNGSGL1BWaeF5AvtCh4SwEuPjeRi7f9APqGw/e4c=,tag:x1NZHZYK6EzsLmUUOmeAYw==,type:comment]
    NEST_EXPORTER_CLIENT_ID: ENC[AES256_GCM,data:dmdxTyv9uKjYM3DZEftJ/x+L4GavfXTRrGvj7ghrhTacOFuj+jKo1xli/qN4nyrztjrDbMwcSec9A8M407n+j9EOR3meqHe2,iv:Ct37TBUfirUtXg+ay6Y0XsXplh8Xpfaj45k5DZ8Hi7o=,tag:mgFnXi4Ue2tMf88omJO+Mw==,type:str]
    NEST_EXPORTER_CLIENT_SECRET: ENC[AES256_GCM,data:UD1aohGwyZE3sE3KpjakcUKN65BlIrkkJQ==,iv:VlUoJ6BrrFEpodxo56T7EImTpxQjRkLNAY87yOEc0c8=,tag:kvZnR7wQtndAvXbuHKQf5A==,type:str]
    NEST_EXPORTER_PROJECT_ID: ENC[AES256_GCM,data:6KQT6LhmIIQkLKAgRT43dD2KQiKwpgwOC9L+HOprmyv5q5PG,iv:XLbmlrbhAASB3Mh4XjF7xHc7dbhUHuHKD5ikbCeIZHE=,tag:eww18pz+Gqx0o59A9jjpDQ==,type:str]
    NEST_EXPORTER_REFRESH_TOKEN: ENC[AES256_GCM,data:dgQSGemS2zbBmRfhjmhY8IUJ2grQLWZtWTIZ2SskvLyUWocBjiP1nRWBmFGxt5GWA8Kkiqxr8rnu/U0IdR0msTO4NAixVPuDKwNbVSxnmW1ArFU6tFZfstDJ6Oeq2hHsgqCmDcEmxg==,iv:tmnHx1C6VaWo100uMwi91naQ8nsQYxkt7I8d9oarBKU=,tag:T+lB9RryMhd5J4qcKYRYiw==,type:str]
    #ENC[AES256_GCM,data:xreiakGScx4=,iv:vBxTIi4MTm1lXybfPd2cBlRAgVpPdOYJM7k5/w3foZU=,tag:GT+r900HcV4+6rpdlNuMPg==,type:comment]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:NLPZjvSFCOY=,iv:1SdLpXRRXSxJiJHQBcv65Vj/6QkB7qEv8M32LzHJyy4=,tag:te5Kf+/qmPizP3kCO0S6gA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-17T14:50:45Z"
    mac: ENC[AES256_GCM,data:sQAFv/Vy/yfdufvHPedRWxFryZ2DA9hnRJK2XriOybiINDgUMrHXGU1l5e3oIUvSuamI6TJXFQjtAR3xzlMKBBriKzdacAjCUahS6sPTX47RXQlz/cjr5bvyl4v6hTlKb/aeY6tDpHg5HxINJyskBZ+dRvUP1BkpFkUwmcY8IO4=,iv:6WmM9npLgGGTOpfFZEcHL2IqrLTXMZyNL7YDpUYodko=,tag:FlaKzrNDCeGePzTrtkzY6g==,type:str]
    pgp:
        - created_at: "2021-05-04T18:50:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx7w+dz/TE0ZAQ/9Gg0GW9oFmQDDyI1z6x9sf+aqfQ89QwhQQIuDZotiW09G
            4YhCfQT+3MyY4qvv7frTBcJdgtZqzVvelVMbqCX/IjGXIqvtJ0yyaet7/Fat+uyX
            j3A3zp/6eaok2du9h4aLjRifx2i570rDIXgS45ZHQ9SvSDDJajlOf5OzdV5lirEl
            WGe/P3Gamj886/hvbyHvMY1zwe0ylNY7jY8a80aqqnPyp1eEQ6NwanrcmiDKZYbu
            dAcQb1p1bIj54OM642+GPj+LdyCPCTm3PqTU/2fyaaWKzXlhzwGSWGDWJKnWoZVU
            H+sAnp3goLjvI8o7bHTdq4JdVl2d0QIQAXTRu4FTWCIeW5bERRYNgXJNqJwocLLc
            iI44FHK6eWsTreR6fj1JF2gO1FhBNmBUN+JJ5FSU3xqmACa1s+wBdqygjgN/+2u0
            wrfUS3fw1k1gqp3xXyr5dF5Li5TOWNfyjdLbsUHhFATrZkTLXqX6TNcirT76Vayi
            iiDgStFGxx/qUZRiNrWwSuZPVk/Gan29Po4M4F+EaHEVHOgSSdJzNPFHtSFOXLHK
            CWpipH33SQbVmIsTCHdjkwT2Cq4NFKsnP4QLhurVBCMp3/u9jQaXunrg30f9M+iz
            qJM6Qh/NA/WgQMO2jygnYfKfgRrAsUX6g11iI7OJtIE5W+ExBcgW4TvriijlA5vS
            XgH6cHZmOEO8u/HzRDomTdT29Zrl3xYHi131TYryS185KYuQSZIqS3w/gf6Pb1ex
            3uJ1OS3XJ4pdrHuXY9uvrS0CC1wYI/AJcduetQ7+ObWy6CC/TycUoCduc9FXHN8=
            =AJbM
            -----END PGP MESSAGE-----
          fp: D3D53D22793960761CDE144C0EF386217DAD811D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
