---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: crds
  path: ./pi/cluster/core
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system