apiVersion: v1
kind: ConfigMap
metadata:
  name: victoria-metrics-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: '1'
data:
  victoria-metrics-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Victoria Metrics
      type: prometheus
      access: proxy
      orgId: 1
      url: http://victoria-metrics-victoria-metrics-single-server.monitoring.svc.cluster.local:8428