apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - volumes.yaml
  - service.yaml

configMapGenerator:
  - name: mosquitto-base-config
    namespace: home-assistant
    files:
      - mosquitto.conf
      - password_file
