---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: home-assistant
  labels:
    app: mosquitto
spec:
  type: LoadBalancer
  loadBalancerIP: "${MQTT_IP}"
  ports:
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    app: mosquitto
