{
 "title": "Home stats",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heating",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nest_thermostat_status", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Living room",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nest_thermostat_actual_temperature",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bedroom",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(hue_sensor_value{type=\"ZLLTemperature\"} / 100) + 1.8",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "(avg by (name) (nest_thermostat_actual_temperature))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "(avg by (name) (nest_thermostat_target_temperature))",
     "legendFormat": "Thermostat "
    },
    {
     "expr": "(avg by (name) (nest_thermostat_status))",
     "legendFormat": "Heating On"
    },
    {
     "expr": "(avg by (location) (openweather_temperature)) > 0",
     "legendFormat": "Outside"
    },
    {
     "expr": "(avg by (name) (hue_sensor_value{type=\"ZLLTemperature\"} / 100)) + 1.8",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Outside",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "openweather_temperature", "legendFormat": "Outside" }
   ]
  },
  {
   "title": "Thermostat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nest_thermostat_target_temperature",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Feels like",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "openweather_feelslike", "legendFormat": "Outside" }
   ]
  },
  { "title": "Humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Living room",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nest_thermostat_humidity", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg by (name) (nest_thermostat_humidity))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "(avg by (location) (openweather_humidity)) > 0",
     "legendFormat": "Outside"
    }
   ]
  },
  {
   "title": "Outside",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "openweather_humidity", "legendFormat": "Outside" }
   ]
  },
  { "title": "Lights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Living Room",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hue_group_on{name=\"Living room\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Hall",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(hue_light_on{name=\"Hall\"} * hue_light_reachable{name=\"Hall\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Lights",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((hue_light_brightness / 254) * hue_light_on * hue_light_reachable) ",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}