---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.15.0
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  values:
    dnsmasq:
      customDnsEntries:
        - address=/.${SECRET_DOMAIN}/${NGINX_IP}

    serviceDns:
      loadBalancerIP: ${DNS_IP}
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer

    serviceDhcp:
      loadBalancerIP: ${DNS_IP}
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer

    extraEnvVars:
      CORS_HOSTS: ${SECRET_DOMAIN}
