---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-config
spec:
  storageClassName: ""
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NFS_SERVER_IP}
    path: "${NFS_BASE_PATH}/Kubernetes/Kubernetes/config/home-assistant"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  namespace: home-assistant
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: home-assistant-config
