apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-exporter
  labels:
    app: speedtest-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-exporter
  template:
    metadata:
      labels:
        app: speedtest-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9112"
    spec:
      containers:
      - name: speedtest-exporter
        image: janwh/speedtest_exporter
        ports:
        - containerPort: 9112
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
spec:
  selector:
    app: speedtest-exporter
  ports:
    - protocol: TCP
      port: 9112