{
 "title": "Node stats",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - (avg (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])))"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(Sum(node_memory_MemTotal_bytes) - Sum(node_memory_MemAvailable_bytes)) / Sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum by (kubernetes_node, mountpoint) (1 - node_filesystem_avail_bytes{mountpoint=~\"/|/mnt/usb\"} / node_filesystem_size_bytes{mountpoint=~\"/|/mnt/usb\"}))",
     "legendFormat": "{{kubernetes_node}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(avg by (kubernetes_node) (1 - irate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum by (kubernetes_node) (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total[5m])) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}} - Write"
    },
    {
     "expr": "sum(rate(node_disk_read_bytes_total[5m])) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}} - Read"
    }
   ]
  },
  {
   "title": "CPU Usage Details",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(avg by (kubernetes_node) (1 - irate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Memory Usage Details",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(sum by (kubernetes_node) (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes))",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(sum by (kubernetes_node) (rate(node_network_receive_bytes_total[5m])))",
     "legendFormat": "{{kubernetes_node}} - Received"
    },
    {
     "expr": "(sum by (kubernetes_node) (rate(node_network_transmit_bytes_total[5m])))",
     "legendFormat": "{{kubernetes_node}} - Transmited"
    }
   ]
  }
 ]
}