---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  values:
    dnsmasq:
      customDnsEntries:
        - address=/.${SECRET_DOMAIN}/${NGINX_IP}
    serviceTCP:
      loadBalancerIP: ${DNS_IP}
      annotations:
        metallb.universe.tf/address-pool: default
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    serviceUDP:
      loadBalancerIP: ${DNS_IP}
      annotations:
        metallb.universe.tf/address-pool: default
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
