---
name: Renovate Annotations

on:
  workflow_dispatch:
  schedule:
  - cron: '0 */12 * * *'

jobs:
  renovate-helm-releases:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1

    - name: Renovate Helm Releases (Pi)
      uses: k8s-at-home/renovate-helm-releases@v1
      with:
        cluster-path: "./pi-cluster"
    
    - name: Renovate Helm Releases (Azure)
      uses: k8s-at-home/renovate-helm-releases@v1
      with:
        cluster-path: "./pi-cluster"

    - name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: renovate-annotations
        delete-branch: true
        title: "Update renovate annotations"
        committer: "David Eadie <theeadie@users.noreply.github.com>"
        author: "David Eadie <theeadie@users.noreply.github.com>"
        commit-message: "update renovate annotations"
        body: |
          Update HelmReleases inorder for Renovate to pick up new versions of Helm charts