---
name: Upgrade Flux

on:
  workflow_dispatch:
  schedule:
  - cron: '0 12 * * *'

jobs:
  flux-upgrade:
    name: Upgrade Flux
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Setup Flux CLI
      uses: fluxcd/flux2/action@main

    - name: Upgrade Flux
      id: upgrade
      run: |
        UGLY_VERSION="$(flux -v)"
        VERSION="v${UGLY_VERSION#*flux version }"
        flux install --version="${VERSION}" \
          --export > ./pi-cluster/flux-system/gotk-components.yaml
        flux install --version="${VERSION}" \
          --export > ./azure/flux-system/gotk-components.yaml
        echo "::set-output name=flux_version::$VERSION"

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: "flux/upgrade-${{ steps.upgrade.outputs.flux_version }}"
        delete-branch: true
        title: "Upgrade Flux components to ${{ steps.upgrade.outputs.flux_version }}"
        committer: "David Eadie <theeadie@users.noreply.github.com>"
        author: "David Eadie <theeadie@users.noreply.github.com>"
        commit-message: "Upgrade Flux components to ${{ steps.upgrade.outputs.flux_version }}"
        body: |
          Release notes: https://github.com/fluxcd/flux2/releases/tag/${{ steps.upgrade.outputs.flux_version }}