apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: "${LETSENCRYPT_EMAIL}"
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          azureDNS:
            clientID: "${AZURE_CLIENT_ID}"
            clientSecretSecretRef:
              name: azuredns-config
              key: client-secret
            subscriptionID: "${AZURE_SUBSCRIPTION_ID}"
            tenantID: "${AZURE_TENANT_ID}"
            resourceGroupName: "${AZURE_DNS_ZONE_RESOURCE_GROUP}"
            hostedZoneName: "${AZURE_DNS_ZONE_NAME}"
            environment: AzurePublicCloud
